services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - consultas_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 12

  notificationservice:
    build:
      context: ./NotificationService
    container_name: notificationservice
    depends_on:
      rabbitmq:
        condition: service_healthy
      sqlserver:
        condition: service_healthy
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: guest
      RABBIT_PASS: guest
      SQL_CONN: "Server=sqlserver,1433;Database=clinica_db;User Id=sa;Password=SDClinica@123;TrustServerCertificate=True;"
    networks:
      - consultas_net

  servico_usuarios:
    build:
      context: ./servicoUsuarios
      dockerfile: Dockerfile
    container_name: servico_usuarios
    ports:
      - "5005:5005"
    environment:
      - CONNECTION_STRING=Server=SistemaDistribuido_db,1433;Database=clinica_db;User Id=sa;Password=SDClinica@123;TrustServerCertificate=True
      - JWT_SECRET=dGhpcy1pcy1hLXJhbmRvbS1qd3QtdG9rZW4tMzItYnl0ZXM=
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - consultas_net

  api:
    build:
      context: ./endpointsInterface
      dockerfile: Dockerfile
    container_name: interface_endpoints
    ports:
      - "8080:80"
    depends_on:
      sqlserver:
        condition: service_healthy
      servico_usuarios:
        condition: service_started
      scheduling:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - SERVICO_USUARIOS_HOST=servico_usuarios
      - SERVICO_USUARIOS_PORT=5005
    networks:
      - consultas_net

  scheduling:
    build:
      context: ./SchedulingService
      dockerfile: Dockerfile
    container_name: scheduling
    ports:
      - "9090:9090"
    depends_on:
      sqlserver:
        condition: service_healthy
      servico_usuarios:
        condition: service_started
    networks:
      - consultas_net

  validation:
    build:
      context: ./ValidationService
      dockerfile: Dockerfile
    container_name: validation
    ports:
      - "1099:1099"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - consultas_net

  validation_interface:
    build:
      context: ./ValidationInterface
      dockerfile: Dockerfile
    container_name: validation_interface
    ports:
      - "9000:9000"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - consultas_net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SistemaDistribuido_db
    environment:
      SA_PASSWORD: "SDClinica@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "SDClinica@123", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - consultas_net

networks:
  consultas_net:
    driver: bridge
